name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive 
    - uses: actions/setup-java@v1
      with:
        java-version: '7'
        java-package: jdk
        architecture: x86
    - name: Create Build Environment
      working-directory: ${{runner.workspace}}/java-cfe/src
      shell: bash
      run: mkdir jcef_build
    - name: Create Build Files
      working-directory: ${{runner.workspace}}/java-cfe/src/jcef_build
      shell: powershell
      run: cmake -G "Visual Studio 14"
    - name: Build
      working-directory: ${{runner.workspace}}/java-cfe/tools
      shell: powershell
      run: compile.bat "win32"
