name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: chromiumembedded/java-cef
        path: java-cef
    - uses: actions/setup-java@v1
      with:
        java-version: '7'
        java-package: jdk
        architecture: x86
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Create Build Environment
      working-directory: ${{runner.workspace}}/bld_jcef-java7/java-cef
      shell: powershell
      run: mkdir "jcef_build"
    - name: Create Build Files
      working-directory: ${{runner.workspace}}/bld_jcef-java7/java-cef/jcef_build
      shell: powershell
      run: cmake -A "Win32" ../
    - name: Build
      working-directory: ${{runner.workspace}}/bld_jcef-java7/java-cef
      shell: powershell
      run: msbuild.exe './jcef_build/jcef.sln' -property:Platform="Win32"
    - name: Compile
      working-directory: ${{runner.workspace}}/bld_jcef-java7/java-cef/tools
      shell: powershell
      run: ./compile.bat "win32"
    - name: Dist
      working-directory: ${{runner.workspace}}/bld_jcef-java7/java-cef/tools
      shell: powershell
      run: ./make_distrib.bat "win32"
