name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive 
    - uses: actions/setup-java@v1
      with:
        java-version: '7'
        java-package: jdk
        architecture: x86
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/java-cfe/build
    - name: Configure CMake
      shell: powershell
      working-directory: ${{runner.workspace}}/java-cfe
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/java-cfe
      shell: powershell
      run: cmake --build . --config $BUILD_TYPE
